FROM node:14-alpine

USER root
ENV NODE_ENV=production
RUN apk update && \
  apk add chromium && \
  apk add chromium-chromedriver

RUN mkdir data && mkdir data/decentralized-testing
ADD ./ /data/decentralized-testing
WORKDIR /data/decentralized-testing
# RUN git clone https://github.com/OskarRubensson/decentralized-testing.git /data/decentralized-testing

# optionally if you want to run npm global bin without specifying path
ENV PATH=$PATH:/home/root/.npm-global/bin

RUN apk --no-cache add --virtual python
RUN npm config set python /usr/bin/python
RUN npm install --production

CMD ["npm", "run", "client"]